### ISSUE TITLE
gpg using insecure memory

### ISSUE THREAD

**Issue by parazyd** [dyne/JaroMail#28]
Just leaving a note for later investigation...

Peeking/fetching/any action using gpg to decrypt the password from passwordstore drops a warning from gpg:
```
gpg: Warning: using insecure memory!
```

This is probably regarding to Jaromail's password handling in general when using pass.

**Comment by jaromil** [comment]
Both for this and for gpg handling in Tomb I wonder if we should start using ASSUAN messaging with gpg-agent.

**Comment by parazyd** [comment]
We could start using ASSUAN, as I believe gnupg2 is what should be a standard nowadays.

The warning is due to an error in distributions' packaging of GnuPG. The executable should be suid - which is not the case in many distros. 

Explained here: https://lists.gnupg.org/pipermail/gnupg-users/2000-October/006769.html
